name: Bug Report
description: File a bug report
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Add a clear and concise description about the issue
      placeholder: Tell us what you see
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Describe the expected behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: I was expecting to see
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: List the steps or a [Storybook](https://elastic.github.io/elastic-charts) example or a reproducible [codesandbox](https://codesandbox.io/s/elastic-charts-playground-87y7g?file=/src/App.tsx) example
      placeholder: |
        1. Go to '...' 
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem
      placeholder: |
        Paste your screenshots here
    validations:
      required: false      
  - type: textarea
    attributes:
      label: Additional context and console logs
      description: Add any other context about the problem and any console error related to the issues
      placeholder: 
    validations:
      required: false
  - type: input
    attributes:
      label: Kibana Cross Issues
      description: Add any [Kibana](https://github.com/elastic/kibana) related issues here
      placeholder: #12345
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
        - label: The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
        - label: Every related Kibana issue is listed under `Kibana Cross Issues` list and the `kibana cross issue` tag is applied

